### ISSUE TITLE
Exclude is only working one time for Query

### ISSUE THREAD

**Issue by Kiragroh** [cutright/DVH-Analytics#125] opened 2020-12-16 11:28 UTC
Hi Dan,

I encountered a strange thing.

With these query settings MRN exclution is not working. 
![screenshot_522](https://user-images.githubusercontent.com/44711812/102342413-7aef9580-3f99-11eb-903a-1e271101c516.png)

It works when one MRN-exclusion is present.

Is this normal?

**Comment by cutright** [comment] 2020-12-16 15:54
Thanks for posting.  I think the issue is in here:
https://github.com/cutright/DVH-Analytics/blob/126f204a73adc8009a9d7a0769158d849abf9e6d/dvha/main.py#L897-L900

When multiple entries are provided for the same SQL column, they're combined with an `OR`. But I think maybe they should be combined with `AND` if the Filter Type is Exclude.

**Comment by Kiragroh** [comment] 2020-12-18 07:29
Thanks Dan. With this simple if statement all is working fine.

DVH-Analytics/dvha/main.py
Line 897:

`
        for table in queries:

            for col in queries_by_sql_column[table]:

                if "!=" in str(queries_by_sql_column[table][col]):
                    queries[table].append("(%s)" % ' AND '.join(queries_by_sql_column[table][col]))
                else:
                    queries[table].append("(%s)" % ' OR '.join(queries_by_sql_column[table][col]))

            queries[table] = ' AND '.join(queries[table])
`

**Comment by cutright** [comment] 2020-12-18 14:54
I think that may fail if you have an include and an exclude for the same column?  I'll come up with a more robust method this weekend.

**Comment by Kiragroh** [comment] 2020-12-18 22:25
You are right. In this case, you get an unwanted Query. But in my Querys it is very unlikely that I mix 'include' and 'exclude' for the same 'category1'. Therefore I am happy about my quick fix. But please add a more robust fix.

**Comment by cutright** [comment] 2021-01-01 19:29
Sorry for the delay, it's not the cleanest, but I think it works as expected.

https://github.com/cutright/DVH-Analytics/blob/ed7aa19e72b006496f71f6b0a2c0e92b4e1370be/dvha/main.py#L902-L913

**Comment by Kiragroh** [comment] 2021-01-02 09:14
Hi Dan, I tried the newest 0.9.2 branch.
I can do anything on my 13'' MacBookPro (BigSur) because the buttons that are cutOff can be access via ContextBar. But Keyboard-Shortcut for Fullscreen (Command+Control+F) or other tricks to get Fullscreen is not working.

<img width="1440" alt="screenshot_70" src="https://user-images.githubusercontent.com/44711812/103454352-5eff2a00-4ce3-11eb-86a0-2f3b37970b09.png">

**Comment by cutright** [comment] 2021-01-02 19:30
fixed in v0.9.2

**Comment by cutright** [comment] 2021-01-05 21:24
Nope. Not fixed yet.
<img width="706" alt="Screen Shot 2021-01-05 at 3 15 26 PM" src="https://user-images.githubusercontent.com/4778878/103700461-1a38f480-4f6a-11eb-99ed-fd8984c759fc.png">

**Comment by cutright** [comment] 2021-01-05 21:24
Nope. Not fixed yet.
<img width="1511" alt="Screen Shot 2021-01-05 at 3 23 58 PM" src="https://user-images.githubusercontent.com/4778878/103700507-28871080-4f6a-11eb-89cd-75a41c17a4d9.png">

**Closed as completed** 2021-01-06 20:22 UTC
Labels: bug
