### ISSUE TITLE
Unable to add variations to Physician ROI

### ISSUE THREAD

**Issue by albertelonjobs** [cutright/DVH-Analytics#48] opened 2020-03-10 17:37 UTC
I tried to add a variation "PTV78" to the example Physician "BBM" and got the following error message.
"'ptv' is already a variation of ptv for BBM".
But apparently it is not. Actually I could not add any new variations to a ROI.

**Comment by cutright** [comment] 2020-03-10 18:18
Which version are you running?  Executable or from python source?  You can get the version in the Help menu -> About

**Comment by albertelonjobs** [comment] 2020-03-10 18:26
I'm running v0.7.3post1 from python source with the command "python
dvha_app.py". I have Python 3.8.0 with the following packages installed.
Thanks!

Package            Version
------------------ ------------
bokeh              2.0.0
cycler             0.10.0
dicompyler-core    0.5.5
fuzzywuzzy         0.18.0
Jinja2             2.11.1
joblib             0.14.1
kiwisolver         1.1.0
MarkupSafe         1.1.1
matplotlib         3.1.2
numpy              1.18.1
packaging          20.3
pandas             0.25.3
patsy              0.5.1
Pillow             7.0.0
pip                20.0.2
psycopg2-binary    2.8.4
pydicom            1.4.2
pyparsing          2.4.6
Pypubsub           4.0.3
python-dateutil    2.8.1
python-Levenshtein 0.12.0
pytz               2019.3
PyYAML             5.3
regressors         0.0.3
scikit-learn       0.22.2.post1
scipy              1.4.1
seaborn            0.10.0
setuptools         46.0.0
Shapely            1.7.0
six                1.13.0
statsmodels        0.11.1
tornado            6.0.4
typing-extensions  3.7.4.1
wheel              0.34.2
wxPython           4.0.7.post2

**Comment by cutright** [comment] 2020-03-10 18:31
One more question... are you adding from the ROI Map module or on the Import screen?

Coincidentally I've made a lot of changes to the ROI Map functionality since last week (including TG263 compliance), I'm about to push a 0.7.4dev3 to PyPI... assuming I can't reproduce your issue on it.

**Comment by albertelonjobs** [comment] 2020-03-10 18:39
I was trying to add from the ROI Map. And there is one more problem. I'm unable to change the DICOM Inbox Directory in the User Setting window. It jumps right back to the default directory after I choose the one I want.

**Comment by cutright** [comment] 2020-03-10 18:44
It looks like the Inbox browse button is editing the Imported?

**Comment by cutright** [comment] 2020-03-10 18:46
Yep, that's an easy fix... will push it soon.

https://github.com/cutright/DVH-Analytics/blob/270ca5f657f7e694ee59d3c0cc28c10ad17c35a9/dvha/dialogs/main.py#L825-L829

**Comment by cutright** [comment] 2020-03-10 18:53
Can you give 0.7.4.dev3 a shot?
`pip install --upgrade dvha==0.7.4dev3`
https://pypi.org/project/dvha/0.7.4.dev3/

I think this will resolve your variation issue if I understand correctly.

Also, you'd be the first to try out the new TG263 functionality.  When you add a new physician, you can check off which anatomical groups and it'll auto populate with TG263 names.

At some point I plan provide a better default map with possible variations.

**Comment by cutright** [comment] 2020-03-10 19:17
Scrap that... there is conflict between adding a variation in the ROI Map and adding on the Import Screen.  Should have it fixed by the end of the day.

**Comment by albertelonjobs** [comment] 2020-03-10 19:33
The Inbox directory is shown correctly now after the selection in User Setting window. However, after I click 'OK', it is not saved.

**Comment by albertelonjobs** [comment] 2020-03-10 20:07
By the way, I'm using Window 10. I can only running the source code. I have never been able to run pip install successfully. It always give me an error as below.
![Capture3](https://user-images.githubusercontent.com/61991041/76354592-23751880-62e9-11ea-81b6-19326df83a6b.JPG)

**Comment by cutright** [comment] 2020-03-10 20:37
**scikit-learn**
You're not the first to have that scikit-learn issue.  To resolve it, I'm about to push a change for requirements.txt to use >=0.21.0, but be aware:
* If you save a regression model and then later upgrade scikit-learn, you *might* not be able to open the model until you downgrade
* The only reason I try to lock in 0.21.0 is due to some geos dll changes that cause problems with PyInstaller when I create the executables, it's not that DVHA cares which version is used.
* I'm not sure why users are having this issue, 0.21.0 exists: https://pypi.org/project/scikit-learn/0.21.0/

**pip install**
If you're comfortable cloning code from GitHub, I suggest sticking to only that and doing a   
`pip uninstall dvha` as many times as needed to remove all versions.  Running from source may inadvertently import from your pip installed dvha rather than the source's local directory.

**Inbox directory**
I'm observing that too, import directory isn't saving either.  In the meantime, you can select a different "inbox" directory on the import screen.

**ROI Map Assignment**
I believe the current state of the 0.7.4dev branch has resolved your original issue.  I'll push a new dev to PyPI after resolving the inbox/import directory issue.  Are you familiar with switching or cloning to another branch to try this out?

**Comment by albertelonjobs** [comment] 2020-03-10 21:18
I'm using GitHub Desktop and I have set my current branch to "v0.7.4dev". Then I clicked "Create Pull Request". It opened up a page in my browser. I clicked the green button "Create pull request". Is this the right way?

**Comment by cutright** [comment] 2020-03-10 21:22
No, you would submit a pull request is you'd like a GitHub project to accept your code.

Maybe this will help? I'm not familiar with GitHub Desktop.
https://help.github.com/en/desktop/contributing-to-projects/switching-between-branches

**Comment by cutright** [comment] 2020-03-10 21:40
If you're not having any luck with GH Desktop:

I've posted a release candidate on PyPI: https://pypi.org/project/dvha/0.7.4rc1/
You *could* do a `pip install dvha==0.7.4.1rc1` if you're not able to switch branches

or

download from here: https://github.com/cutright/DVH-Analytics/archive/v0.7.4dev.zip

**Comment by albertelonjobs** [comment] 2020-03-10 21:43
I think I have switched the branch. I'm running on v0.7.4rc1 now. It seems the ROI variation problem has been fixed. Thank you very much!

**Comment by cutright** [comment] 2020-03-10 21:48
Thanks for your patience... inching closer to a solid v1.0.

**Comment by cutright** [comment] 2020-03-10 21:54
I'm going to close this issue, but please feel free to open a new one if you find something else (or I'll reopen this one if it's not actually fixed).

I'd like to give v0.7.4rc1 at least a day or two before pushing to master and posting executables.  If you find any other quick issues like these, I'll try to sneak those fixes in with v0.7.4.

**Closed as completed by cutright** 2020-03-10 21:54 UTC
