### ISSUE TITLE
2 plans for the same structure set

### ISSUE THREAD

**Issue by Kiragroh** [cutright/DVH-Analytics#71] opened 2020-05-01 15:12 UTC
Hi Dan,

I tested a DataSet today that had more than one plan variant for the same structure set. Therefore the import queue looks something like that: 
![2plansForsamStructureSet](https://user-images.githubusercontent.com/44711812/80815974-ed5c6280-8bce-11ea-9c20-571df3432880.PNG)

The DicomParser will have problems after the first imported plan.

My temporary fix is: I copy the structure set and import iterative because the importer will skip the copied structure set in the first import run.

Here is a sample patient. Hope you can help. Maybe it would work with dose summation but because these are plans for the same PTV, I deactivated dose summation.
[Dan_TestFiles2_OneStructureSet for multiple plans.zip](https://github.com/cutright/DVH-Analytics/files/4564939/Dan_TestFiles2_OneStructureSet.for.multiple.plans.zip)

**Comment by cutright** [comment] 2020-05-01 16:04
Is this on `v0.7.8`? Did it happen on before `v0.7.8`?

**Comment by Kiragroh** [comment] 2020-05-01 16:09
Before, I did not have many of those cases.
In the past, I used an anonymizer for the second plan. But for studies where you want to import many plans for the same structure set it would be a lot of work.
And I think the copy trick worked better in older versions because I could change the imported Study-UID (can this be?). Now I could not change the study ID in the importer

**Comment by cutright** [comment] 2020-05-01 16:26
I'm unable to reproduce this in `v0.7.8`, but I don't *think* `v0.7.7` should be different.  I was able to import with and without the dose summation (separately).  Perhaps you didn't click apply after changing the `StudyInstanceUID` of the 2nd plan?  Having the same `StudyInstanceUID` for both plans worked as well though.

Can you provide some screenshots to help me understand better?

**Comment by cutright** [comment] 2020-05-01 16:42
I should also note that you don't need to change the `StudyInstanceUID`.  DVHA will automatically append _[plan#] to the end if you have multiple plans and you did not apply the dose summation.

**Comment by Kiragroh** [comment] 2020-05-01 16:49
I found the solution. I forget to look in the terminal when the importer freeze.
![solution](https://user-images.githubusercontent.com/44711812/80822976-09b2cc00-8bdc-11ea-83d7-9d3c5a2a76d2.PNG)
Of course, I have to click 'Leave files in inbox' if I want to use a file twice. Sorry to even ask this question.^^

**Comment by cutright** [comment] 2020-05-01 17:04
This might still be a bug?

Seems to me I shouldn't have files move until the Study is complete, not just the plan.  I'll have to check the code to verify when it happens.

**Comment by cutright** [comment] 2020-05-02 14:49
DVHA maintains a queue of files to move, but doesn't move them until the final plan of the study.
https://github.com/cutright/DVH-Analytics/blob/b16805a550c01efcdab72e89517dbf1249c389a2/dvha/models/import_dicom.py#L1271-L1277

So sounds like your conclusion is right.

However, it looks there's a separate issue with `roi_map.py`?  I'll look into that.

**Comment by cutright** [comment] 2020-05-07 00:15
As a side note, investigating those `roi_map.py` issues in your screen shot led me to find some significant bugs around adding, editing, and deleting physicians in the ROI Map.  Definitely worth upgrading to `v0.7.9`... pushing it shortly.

I think it's safe to close this issue now?

**Closed as completed** 2020-05-07 10:11 UTC
